/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import java.util.Date;
import java.text.*;
import javax.swing.table.DefaultTableModel;

public class frmPonente extends javax.swing.JInternalFrame {

    String Codigo;
    double resultado;
    int registros;
    
    public frmPonente() {
        initComponents();
        activarBotones(true,false,false,true);
        actualizarTabla();
        desactivarCampos();
    }
    
    void limpiarCampos(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtNacionalidad.setText("");
        txtEspecialidad.setText("");
        lblFoto.setText("");
        
    }
    void activarCampos(){
        txtNombres.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtNacionalidad.setEnabled(true);
        txtEspecialidad.setEnabled(true);
        lblFoto.setEnabled(true);
    }
    void desactivarCampos(){
        txtNombres.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtNacionalidad.setEnabled(false);
        txtEspecialidad.setEnabled(false);
        lblFoto.setEnabled(false);
    }
    void activarBotones(boolean n,boolean g,boolean m,boolean e){
        btnNuevo.setEnabled(n);
        btnGrabar.setEnabled(g);
        btnModificar.setEnabled(m);
        btnEliminar.setEnabled(e);
    }
    
  
     void actualizarTabla(){
     String titulos[] = {"Id","Nombres","Apellidos","Nacionalidad", "Especialidad","Foto"};  
     clsPonente Ponentes = new clsPonente();
     ArrayList<clsEntidadPonente> ponente =Ponentes.listarPonente();
     Iterator iterator = ponente.iterator();
     DefaultTableModel dtm = new DefaultTableModel(null,titulos);
     String fila[]=new String [6];
     while (iterator.hasNext()){
         clsEntidadPonente Pon = new clsEntidadPonente();
         Pon = (clsEntidadPonente) iterator.next();
         fila[0] = Pon.getId_pon();
         fila[1] = String.valueOf(Pon.getNomb_pon());
         fila[2] = String.valueOf(Pon.getApe_pon());
         fila[3] = String.valueOf(Pon.getNacionalidad_pon());
         fila[4] = String.valueOf(Pon.getEspecialidad_pon());
         fila[5] = String.valueOf(Pon.getFoto_pon());
         dtm.addRow(fila);
                         
     }
        tblPonente.setModel(dtm);
     } 
    void seleccionarTabla(){
         DefaultTableModel dtm = new DefaultTableModel();
         registros = tblPonente.getSelectedRow();
         if(registros==-1){
             JOptionPane.showMessageDialog(this, "se debe seleccionar un registro");
         }else{
             dtm = (DefaultTableModel)tblPonente.getModel();
             Codigo=((String)dtm.getValueAt(registros, 0));
             txtNombres.setText((String)dtm.getValueAt(registros, 1));
             txtApellidos.setText((String)dtm.getValueAt(registros, 2));
             txtNacionalidad.setText((String)dtm.getValueAt(registros, 3));
             txtEspecialidad.setText((String)dtm.getValueAt(registros, 4));
             lblFoto.setText((String)dtm.getValueAt(registros, 5));
             activarBotones(true,false,true,true);
             activarCampos();
         }
   
     }
    
    void recorrerTabla(){
         DefaultTableModel dtm = new DefaultTableModel(); 
         if(registros==-1){
             JOptionPane.showMessageDialog(this, "se debe seleccionar un registro");
         }else{
             dtm = (DefaultTableModel)tblPonente.getModel();
             Codigo=((String)dtm.getValueAt(registros, 0));
             txtNombres.setText((String)dtm.getValueAt(registros, 1));
             txtApellidos.setText((String)dtm.getValueAt(registros, 2));
             txtNacionalidad.setText((String)dtm.getValueAt(registros, 3));
             txtEspecialidad.setText((String)dtm.getValueAt(registros, 4));
             lblFoto.setText((String)dtm.getValueAt(registros, 5));
             activarBotones(true,false,true,true);
             activarCampos();
         }     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPonente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        txtApellidos = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mantenimiento de Ponente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Especialidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, 30));

        tblPonente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPonente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPonenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPonente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 490, 110));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Foto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Apellidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nacionalidad:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblFoto.setText("jLabel2");
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 110, 90));

        btnNuevo.setBackground(new java.awt.Color(153, 255, 51));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computer_remove.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rewind.png"))); // NOI18N
        btnPrimero.setText("Primero");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/skip_backward.png"))); // NOI18N
        btnAnterior.setText("<<Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/skip_forward.png"))); // NOI18N
        btnSiguiente.setText("siguiente>>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fast_forward.png"))); // NOI18N
        btnUltimo.setText("Ultimo");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, 30));
        getContentPane().add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, 30));
        getContentPane().add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPonenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPonenteMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblPonenteMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        activarCampos();
        txtNombres.requestFocus();
        activarBotones(false,true,false,false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        
        clsPonente ponente = new clsPonente();
        clsEntidadPonente pon = new clsEntidadPonente();
        pon.setNomb_pon(String.valueOf(txtNombres.getText()));
        pon.setApe_pon(String.valueOf(txtApellidos.getText()));
        pon.setNacionalidad_pon(String.valueOf(txtNacionalidad.getText()));
        pon.setEspecialidad_pon(String.valueOf(txtEspecialidad.getText()));
        pon.setFoto_pon(String.valueOf(lblFoto.getText()));

        ponente.AgregarPonente(pon);
        actualizarTabla();
        activarBotones(true,false,false,false);
        desactivarCampos();
        limpiarCampos();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        
        clsPonente ponente = new clsPonente();
        clsEntidadPonente pon = new clsEntidadPonente();
        pon.setNomb_pon(String.valueOf(txtNombres.getText()));
        pon.setApe_pon(String.valueOf(txtApellidos.getText()));
        pon.setNacionalidad_pon(String.valueOf(txtNacionalidad.getText()));
        pon.setEspecialidad_pon(String.valueOf(txtEspecialidad.getText()));
        pon.setFoto_pon(String.valueOf(lblFoto.getText()));

        ponente.ModificarPonente(Codigo, pon);
        actualizarTabla();
        desactivarCampos();
        limpiarCampos();
        activarBotones(true,false,false,false);

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Estas seguro de Eliminar el registro?",
            "Pregunta",0);
        if(r==0){
            clsPonente oper = new clsPonente();
            oper.EliminarPonente(Codigo);
            actualizarTabla();
            limpiarCampos();

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Deseas Cancelar?",
            "Pregunta",0);
        if(r==0){
            limpiarCampos();
            txtNombres.setEnabled(true);
            txtApellidos.requestFocus();
           
            activarBotones(true,false,false,false);
            desactivarCampos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        registros = 0;
        recorrerTabla();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        registros =registros-1;
        if(registros<0){
            registros = 0;
            JOptionPane.showMessageDialog(null, "Primer Registro");

        }
        recorrerTabla();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        registros =registros+1;
        if(registros>tblPonente.getRowCount()-1){
            registros = tblPonente.getRowCount()-1;
            JOptionPane.showMessageDialog(null, "Ultimo Registro");

        }
        recorrerTabla();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        registros = tblPonente.getRowCount()-1;
        recorrerTabla();
    }//GEN-LAST:event_btnUltimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tblPonente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
