/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import java.util.Date;
import java.text.*;
import javax.swing.table.DefaultTableModel;

public class frmParticipante extends javax.swing.JInternalFrame {

    String Codigo;
    double resultado;
    int registros;
    
    
    public frmParticipante() {
        initComponents();
        activarBotones(true,false,false,true);
        actualizarTabla();
        desactivarCampos();
    }
    
    void limpiarCampos(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        txtCelular.setText("");
       
        
    }
    void activarCampos(){
        txtNombres.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtEmail.setEnabled(true);
        txtCelular.setEnabled(true);
        
    }
    void desactivarCampos(){
        txtNombres.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCelular.setEnabled(false);
    }
    void activarBotones(boolean n,boolean g,boolean m,boolean e){
        btnNuevo.setEnabled(n);
        btnGrabar.setEnabled(g);
        btnModificar.setEnabled(m);
        btnEliminar.setEnabled(e);
    }
    
  
     void actualizarTabla(){
     String titulos[] = {"Id","Nombres","Apellidos","Email","Celular"};  
     clsParticipante Participantes = new clsParticipante();
     ArrayList<clsEntidadParticipante> participante =Participantes.listarParticipante();
     Iterator iterator = participante.iterator();
     DefaultTableModel dtm = new DefaultTableModel(null,titulos);
     String fila[]=new String [5];
     while (iterator.hasNext()){
         clsEntidadParticipante Par = new clsEntidadParticipante();
         Par = (clsEntidadParticipante) iterator.next();
         fila[0] = Par.getId_par();
         fila[1] = String.valueOf(Par.getNomb_par());
         fila[2] = String.valueOf(Par.getApe_par());
         fila[3] = String.valueOf(Par.getEmail_par());
         fila[4] = String.valueOf(Par.getCelular_par());
         dtm.addRow(fila);
                         
     }
        tblParticipante.setModel(dtm);
     } 
    void seleccionarTabla(){
         DefaultTableModel dtm = new DefaultTableModel();
         registros = tblParticipante.getSelectedRow();
         if(registros==-1){
             JOptionPane.showMessageDialog(this, "se debe seleccionar un registro");
         }else{
             dtm = (DefaultTableModel)tblParticipante.getModel();
             Codigo=((String)dtm.getValueAt(registros, 0));
             txtNombres.setText((String)dtm.getValueAt(registros, 1));
             txtApellidos.setText((String)dtm.getValueAt(registros, 2));
             txtEmail.setText((String)dtm.getValueAt(registros, 3));
             txtCelular.setText((String)dtm.getValueAt(registros, 4));
             
             activarBotones(true,false,true,true);
             activarCampos();
         }
   
     }
    
    void recorrerTabla(){
         DefaultTableModel dtm = new DefaultTableModel(); 
         if(registros==-1){
             JOptionPane.showMessageDialog(this, "se debe seleccionar un registro");
         }else{
             dtm = (DefaultTableModel)tblParticipante.getModel();
             Codigo=((String)dtm.getValueAt(registros, 0));
             txtNombres.setText((String)dtm.getValueAt(registros, 1));
             txtApellidos.setText((String)dtm.getValueAt(registros, 2));
             txtEmail.setText((String)dtm.getValueAt(registros, 3));
             txtCelular.setText((String)dtm.getValueAt(registros, 4));
             activarBotones(true,false,true,true);
             activarCampos();
         }     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParticipante = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mantenimiento de Participante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        tblParticipante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblParticipante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblParticipanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblParticipante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 520, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Apellidos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computer_remove.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rewind.png"))); // NOI18N
        btnPrimero.setText("Primero");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/skip_backward.png"))); // NOI18N
        btnAnterior.setText("<<Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/skip_forward.png"))); // NOI18N
        btnSiguiente.setText("siguiente>>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fast_forward.png"))); // NOI18N
        btnUltimo.setText("Ultimo");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, 30));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, 30));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 180, 30));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblParticipanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblParticipanteMouseClicked
       seleccionarTabla();
    }//GEN-LAST:event_tblParticipanteMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        activarCampos();
        txtCelular.requestFocus();
        activarBotones(false,true,false,false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        clsParticipante participante = new clsParticipante();
        clsEntidadParticipante par = new clsEntidadParticipante();
        par.setNomb_par(String.valueOf(txtNombres.getText()));
        par.setApe_par(String.valueOf(txtApellidos.getText()));
        par.setEmail_par(String.valueOf(txtEmail.getText()));
        par.setCelular_par(String.valueOf(txtCelular.getText()));

        participante.AgregarParticipante(par);
        actualizarTabla();
        activarBotones(true,false,false,false);
        desactivarCampos();
        limpiarCampos();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        clsParticipante participante = new clsParticipante();
        clsEntidadParticipante par = new clsEntidadParticipante();
        par.setNomb_par(String.valueOf(txtNombres.getText()));
        par.setApe_par(String.valueOf(txtApellidos.getText()));
        par.setEmail_par(String.valueOf(txtEmail.getText()));
        par.setCelular_par(String.valueOf(txtCelular.getText()));

        participante.ModificarParticipante(Codigo, par);
        actualizarTabla();
        desactivarCampos();
        limpiarCampos();
        activarBotones(true,false,false,false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Estas seguro de Eliminar el registro?",
            "Pregunta",0);
        if(r==0){
            clsParticipante par = new clsParticipante();
            par.EliminarParticipante(Codigo);
            actualizarTabla();
            limpiarCampos();

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Deseas Cancelar?",
            "Pregunta",0);
       if(r == 0){
         
           limpiarCampos();
           activarBotones(true,false,false,false);
           desactivarCampos();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        registros = 0;
        recorrerTabla();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        registros =registros-1;
        if(registros<0){
            registros = 0;
            JOptionPane.showMessageDialog(null, "Primer Registro");

        }
        recorrerTabla();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        registros =registros+1;
        if(registros>tblParticipante.getRowCount()-1){
            registros = tblParticipante.getRowCount()-1;
            JOptionPane.showMessageDialog(null, "Ultimo Registro");

        }
        recorrerTabla();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        registros = tblParticipante.getRowCount()-1;
        recorrerTabla();
    }//GEN-LAST:event_btnUltimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblParticipante;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
