/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class frmUsuarios extends javax.swing.JInternalFrame {

   String codigo;
           int registros;
           String id[]=new String[100];
           static int intContador;
    
    
    public frmUsuarios() {
        initComponents();
        cargarcomboNivel();
        cargarcomboEstado();
        desactivarCampos();
        activarBotones(true,false,false,false);
        actualizarTabla();
        
        
    }
    
    void activarCampos(){
        txtUsuario.setEnabled(true);
        txtPassword.setEnabled(true);
        cboNivel.setEnabled(true);
        cboEstado.setEnabled(true);
    }
    
    void desactivarCampos(){
        txtUsuario.setEnabled(false);
        txtPassword.setEnabled(false);
        cboNivel.setEnabled(false);
        cboEstado.setEnabled(false);
    }
    
      void limpiarCampos(){
        txtUsuario.setText("");
        txtPassword.setText("");
    }
      
       void activarBotones(boolean n,boolean g,boolean m,boolean e){
        btnNuevo.setEnabled(n);
        btnGrabar.setEnabled(g);
        btnModificar.setEnabled(m);
        btnEliminar.setEnabled(e);
    }
       
        void cargarcomboNivel(){
        cboNivel.removeAllItems();
        cboNivel.addItem("Administrador");
        cboNivel.addItem("Cliente");
        cboNivel.addItem("Usuario");
    }
    
        void cargarcomboEstado(){
        cboEstado.removeAllItems();
        cboEstado.addItem("Activo");
        cboEstado.addItem("Inactivo");
    }
        
        void actualizarTabla(){
        String titulos[] = {"Codigo","Usuario","Password","Nivel","Estado"};
        clsUsuario usuarios = new clsUsuario();
        ArrayList<clsEntidadUsuario> user = usuarios.listarUsuarios();
        Iterator iterator = user.iterator();
        DefaultTableModel dtm = new DefaultTableModel(null,titulos);
        
        String fila[] = new String[5];
        while(iterator.hasNext()){
            clsEntidadUsuario usu = new clsEntidadUsuario();
            usu = (clsEntidadUsuario) iterator.next();
            fila[0] = usu.getId_usu();
            fila[1] = usu.getNomb_usu();
            fila[2] = usu.getPass_usu();
            fila[3] = usu.getNivel_usu();
            fila[4] = usu.getEstado_usu();
            
            dtm.addRow(fila);
            
            tblUsuario.setModel(dtm);
            
            
        }
      }
        
        
    void seleccionarTabla(){
        int fila;
        DefaultTableModel dtm = new DefaultTableModel();
        fila = tblUsuario.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar un R");
            
        }else{
            dtm = (DefaultTableModel)tblUsuario.getModel();
            txtid.setText((String) dtm.getValueAt(fila, 0));
            txtUsuario.setText((String)dtm.getValueAt(fila, 1));
            txtPassword.setText((String)dtm.getValueAt(fila, 2));
            cboNivel.setSelectedItem((String) dtm.getValueAt(fila,3));
            cboEstado.setSelectedItem((String) dtm.getValueAt(fila,4));
            activarBotones(true,false,true,true);
            activarCampos();
  
            
        }
    }
        

        
        
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cboNivel = new javax.swing.JComboBox();
        cboEstado = new javax.swing.JComboBox();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mantenimiento de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nivel:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        cboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNivelActionPerformed(evt);
            }
        });
        getContentPane().add(cboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 80, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 80, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 80, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, -1));

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 540, 180));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Usuario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
        activarCampos();
        txtUsuario.requestFocus();
        activarBotones(false,true,false,false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        clsUsuario usuario = new clsUsuario();
        clsEntidadUsuario usu = new clsEntidadUsuario();
        usu.setId_usu(txtid.getText());
        usu.setNomb_usu(txtUsuario.getText());
        usu.setPass_usu(txtPassword.getText());
        usu.setNivel_usu(cboNivel.getSelectedItem().toString());
        usu.setEstado_usu(cboEstado.getSelectedItem().toString());
        usuario.modificarUsuario(codigo, usu);
        actualizarTabla();
        limpiarCampos();
        activarBotones(true,true,true,false);
        desactivarCampos();
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       clsUsuario usuario = new clsUsuario();
        clsEntidadUsuario usu = new clsEntidadUsuario();
        usu.setId_usu(txtid.getText());
        usu.setNomb_usu(txtUsuario.getText());
        usu.setPass_usu(txtPassword.getText());
        usu.setNivel_usu(cboNivel.getSelectedItem().toString());
        usu.setEstado_usu(cboEstado.getSelectedItem().toString());
        usuario.modificarUsuario(codigo, usu);
        actualizarTabla();
        limpiarCampos();
        activarBotones(true,true,true,false);
        desactivarCampos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int r;
       r = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Eliminar el registro?","Pregunta",0);
       
       if(r == 0){
           clsUsuario usuarios = new clsUsuario();
           usuarios.eliminarUsuario(codigo);
           actualizarTabla();
           limpiarCampos();
           desactivarCampos();
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int r;
       r = JOptionPane.showConfirmDialog(null, "¿Esta seguro de cancelar la operacion?","Pregunta",0);
       
       if(r == 0){
         
           limpiarCampos();
           activarBotones(true,false,false,false);
           desactivarCampos();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNivelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboNivel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables


}
