/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import img.ImagenFondo;
import javax.swing.ImageIcon;
import java.text.*;
import java.util.Date;
import javax.swing.*;


public class MDIPrincipal extends javax.swing.JFrame {

    public int estado;
    public String usuario,nivel;
    public MDIPrincipal() {
        initComponents();
        Escritorio1.setBorder(new ImagenFondo());
        Fecha();
    }
    
 
  
    
    
   public void Fecha(){
        Date date = new Date();
        String format = new String("dd/MM/YYYY");
        SimpleDateFormat formato = new SimpleDateFormat(format);
        lblFecha.setText(formato.format(date));
    }
   
   
     public void abrirUsuarios(){
        Presentacion.frmUsuarios usur = new Presentacion.frmUsuarios();
        Escritorio1.add(usur);
        usur.show();
    }
     
      public void abrirPonente(){
        Presentacion.frmPonente usur = new Presentacion.frmPonente();
        Escritorio1.add(usur);
        usur.show();
    }
     
      public void abrirOrganizador(){
        Presentacion.frmOrganizador usur = new Presentacion.frmOrganizador();
        Escritorio1.add(usur);
        usur.show();
    }
     
      public void abrirRecurso(){
        Presentacion.frmRecurso usur = new Presentacion.frmRecurso();
        Escritorio1.add(usur);
        usur.show();
    }
      
       public void abrirParticipante(){
        Presentacion.frmParticipante usur = new Presentacion.frmParticipante();
        Escritorio1.add(usur);
        usur.show();
    }
       
       
       
        public void abrirTipoComision(){
        Presentacion.frmTipoComision tipocomi = new Presentacion.frmTipoComision();
        Escritorio1.add(tipocomi);
        tipocomi.show();
    }
       
       
       
       
        public void abrirConsultaUsuario(){
        Presentacion.FrmConsultaUsuario usur = new Presentacion.FrmConsultaUsuario();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaCriterioUsuario(){
        Presentacion.FrmConsultaUsuarioCriterio usur = new Presentacion.FrmConsultaUsuarioCriterio();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaOrganizador(){
        Presentacion.FrmConsultaOrganizador usur = new Presentacion.FrmConsultaOrganizador();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaOrganizadorCriterio(){
        Presentacion.FrmConsultaOrganizadorCriterio usur = new Presentacion.FrmConsultaOrganizadorCriterio();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaPonente(){
        Presentacion.FrmConsultaPonente usur = new Presentacion.FrmConsultaPonente();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaPonenteCriterio(){
        Presentacion.FrmConsultaPonenteCriterio usur = new Presentacion.FrmConsultaPonenteCriterio();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaRecurso(){
        Presentacion.FrmConsultaRecursos usur = new Presentacion.FrmConsultaRecursos();
        Escritorio1.add(usur);
        usur.show();
    }
      
        public void abrirConsultaRecursosCriterio(){
        Presentacion.FrmConsultaRecursosCriterio usur = new Presentacion.FrmConsultaRecursosCriterio();
        Escritorio1.add(usur);
        usur.show();
    }
        
        
        public void abrirConsultaParticipante(){
        Presentacion.FrmConsultaParticipante usur = new Presentacion.FrmConsultaParticipante();
        Escritorio1.add(usur);
        usur.show();
    }
        
        public void abrirConsultaParticipanteCriterio(){
        Presentacion.FrmConsultaParticipanteCriterio usur = new Presentacion.FrmConsultaParticipanteCriterio();
        Escritorio1.add(usur);
        usur.show();
    }
        
     public void Salir(){
        int r;
        r = JOptionPane.showConfirmDialog(Escritorio1, "¿Estas Seguro de Salir del Sistema?","Salir",0);
        if(r==0){
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnEventos = new javax.swing.JButton();
        btnOrganizador = new javax.swing.JButton();
        btnPonentes = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnParticipante = new javax.swing.JButton();
        btnRecurso = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Escritorio1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MMantenimiento = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuTipoComision = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MReporte = new javax.swing.JMenu();
        MCertificado = new javax.swing.JMenu();
        MConsulta = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        MAyuda = new javax.swing.JMenu();
        MSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        btnEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/multiple.png"))); // NOI18N
        btnEventos.setText("Eventos");
        btnEventos.setFocusable(false);
        btnEventos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEventos.setMaximumSize(new java.awt.Dimension(67, 49));
        btnEventos.setMinimumSize(new java.awt.Dimension(67, 49));
        btnEventos.setPreferredSize(new java.awt.Dimension(67, 49));
        btnEventos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEventos);

        btnOrganizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/hand.png"))); // NOI18N
        btnOrganizador.setText("Organizador");
        btnOrganizador.setFocusable(false);
        btnOrganizador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrganizador.setMaximumSize(new java.awt.Dimension(67, 49));
        btnOrganizador.setMinimumSize(new java.awt.Dimension(67, 49));
        btnOrganizador.setPreferredSize(new java.awt.Dimension(67, 49));
        btnOrganizador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrganizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizadorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOrganizador);

        btnPonentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/man-figure.png"))); // NOI18N
        btnPonentes.setText("Ponentes");
        btnPonentes.setFocusable(false);
        btnPonentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPonentes.setMaximumSize(new java.awt.Dimension(67, 49));
        btnPonentes.setMinimumSize(new java.awt.Dimension(67, 49));
        btnPonentes.setPreferredSize(new java.awt.Dimension(67, 49));
        btnPonentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPonentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonentesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPonentes);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/man.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setFocusable(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setMaximumSize(new java.awt.Dimension(67, 49));
        btnUsuario.setMinimumSize(new java.awt.Dimension(67, 49));
        btnUsuario.setPreferredSize(new java.awt.Dimension(67, 49));
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        btnParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/direction-path.png"))); // NOI18N
        btnParticipante.setText("Participante");
        btnParticipante.setFocusable(false);
        btnParticipante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParticipante.setMaximumSize(new java.awt.Dimension(67, 49));
        btnParticipante.setMinimumSize(new java.awt.Dimension(67, 49));
        btnParticipante.setPreferredSize(new java.awt.Dimension(67, 49));
        btnParticipante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParticipanteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnParticipante);

        btnRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/share.png"))); // NOI18N
        btnRecurso.setText("Recursos");
        btnRecurso.setFocusable(false);
        btnRecurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecurso.setMaximumSize(new java.awt.Dimension(67, 49));
        btnRecurso.setMinimumSize(new java.awt.Dimension(67, 49));
        btnRecurso.setPreferredSize(new java.awt.Dimension(67, 49));
        btnRecurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRecurso);

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/keyboard.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setFocusable(false);
        btnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultas.setMaximumSize(new java.awt.Dimension(67, 49));
        btnConsultas.setMinimumSize(new java.awt.Dimension(67, 49));
        btnConsultas.setPreferredSize(new java.awt.Dimension(67, 49));
        btnConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultas);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ipad.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setMaximumSize(new java.awt.Dimension(67, 49));
        btnReportes.setMinimumSize(new java.awt.Dimension(67, 49));
        btnReportes.setPreferredSize(new java.awt.Dimension(67, 49));
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReportes);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button-record.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setMaximumSize(new java.awt.Dimension(67, 49));
        btnSalir.setMinimumSize(new java.awt.Dimension(67, 49));
        btnSalir.setPreferredSize(new java.awt.Dimension(67, 49));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, 60));

        Escritorio1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Escritorio1Layout = new javax.swing.GroupLayout(Escritorio1);
        Escritorio1.setLayout(Escritorio1Layout);
        Escritorio1Layout.setHorizontalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        Escritorio1Layout.setVerticalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        getContentPane().add(Escritorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, 1200, 630));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("SISTEMA SEMCOP EVENTS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 340, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nivel:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Bienvenido:");

        lblFecha.setForeground(new java.awt.Color(255, 0, 0));
        lblFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUsuario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblUsuarioComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Fecha:");

        lblNivel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(51, 51, 51));
        lblNivel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 860, 50));

        jMenuBar1.setForeground(new java.awt.Color(255, 51, 0));

        MArchivo.setText("Archivo");

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MArchivo.add(jMenuItem1);

        jMenuBar1.add(MArchivo);

        MMantenimiento.setText("Mantenimiento");

        jMenuItem2.setText("Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MMantenimiento.add(jMenuItem2);

        jMenuItem3.setText("Ponente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MMantenimiento.add(jMenuItem3);

        jMenuItem4.setText("Evento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MMantenimiento.add(jMenuItem4);

        menuTipoComision.setText("Comision");
        menuTipoComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipoComisionActionPerformed(evt);
            }
        });
        MMantenimiento.add(menuTipoComision);

        jMenuItem6.setText("Asistente");
        MMantenimiento.add(jMenuItem6);

        jMenuItem7.setText("Gastos");
        MMantenimiento.add(jMenuItem7);

        jMenuBar1.add(MMantenimiento);

        MReporte.setText("Reporte");
        jMenuBar1.add(MReporte);

        MCertificado.setText("Certificado");
        jMenuBar1.add(MCertificado);

        MConsulta.setText("Consulta");

        jMenuItem8.setText("Consulta Usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem8);

        jMenuItem9.setText("Consulta Usuario por Criterio");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem9);

        jMenuItem10.setText("Consultar Organizador");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem10);

        jMenuItem11.setText("Consultar Organizador por Criterio");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem11);

        jMenuItem12.setText("Consultar Ponente");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem12);

        jMenuItem13.setText("Consultar Ponente por Criterio");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem13);

        jMenuItem14.setText("Consultar Recursos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem14);

        jMenuItem15.setText("Consultar Recursos por Criterio");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem15);

        jMenuItem16.setText("Consultar Participantes");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem16);

        jMenuItem17.setText("Consultar Participantes por Criterio");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        MConsulta.add(jMenuItem17);

        jMenuBar1.add(MConsulta);

        MAyuda.setText("Ayuda");
        jMenuBar1.add(MAyuda);

        MSalir.setText("Salir");
        jMenuBar1.add(MSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Salir();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       abrirPonente();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnOrganizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizadorActionPerformed
       abrirOrganizador();
    }//GEN-LAST:event_btnOrganizadorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lblUsuarioComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblUsuarioComponentShown
      
    }//GEN-LAST:event_lblUsuarioComponentShown

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnPonentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonentesActionPerformed
        abrirPonente();
    }//GEN-LAST:event_btnPonentesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticipanteActionPerformed
        abrirParticipante();
    }//GEN-LAST:event_btnParticipanteActionPerformed

    private void btnRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursoActionPerformed
        abrirRecurso();
    }//GEN-LAST:event_btnRecursoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        abrirConsultaUsuario();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        abrirConsultaCriterioUsuario();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        abrirConsultaOrganizador();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        abrirConsultaOrganizadorCriterio();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        abrirConsultaPonente();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        abrirConsultaPonenteCriterio();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
       abrirUsuarios();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lblUsuario.setText("Desconectado");
        if(estado==1){
            lblUsuario.setText(usuario);
            lblNivel.setText(nivel);
        }
        if(lblUsuario.getText().equals("Desconectado")){
            //menus desactivados
            MArchivo.setEnabled(false);
            MMantenimiento.setEnabled(false);
            MConsulta.setEnabled(false);
            MReporte.setEnabled(false);
            MAyuda.setEnabled(false);
            MCertificado.setEnabled(false);
            //botones desactivados
            btnEventos.setEnabled(false);
            btnUsuario.setEnabled(false);
            btnOrganizador.setEnabled(false);
            btnPonentes.setEnabled(false);
            btnConsultas.setEnabled(false);
            btnParticipante.setEnabled(false);
            btnEventos.setEnabled(false);
            btnRecurso.setEnabled(false);
            btnReportes.setEnabled(false);
            
        }
    }//GEN-LAST:event_formComponentShown

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        abrirConsultaRecurso();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        abrirConsultaRecursosCriterio();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
       abrirConsultaParticipante();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
      abrirConsultaParticipanteCriterio();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abrirUsuarios();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuTipoComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipoComisionActionPerformed
      abrirTipoComision();
    }//GEN-LAST:event_menuTipoComisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio1;
    private javax.swing.JMenu MArchivo;
    private javax.swing.JMenu MAyuda;
    private javax.swing.JMenu MCertificado;
    private javax.swing.JMenu MConsulta;
    private javax.swing.JMenu MMantenimiento;
    private javax.swing.JMenu MReporte;
    private javax.swing.JMenu MSalir;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnOrganizador;
    private javax.swing.JButton btnParticipante;
    private javax.swing.JButton btnPonentes;
    private javax.swing.JButton btnRecurso;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuTipoComision;
    // End of variables declaration//GEN-END:variables
}
